In [1]:
import json
import requests
import pandas as pd
import numpy as np

import sqlite3

In [39]:
conn = sqlite3.connect('data.sqlite')
us_data_df = pd.read_sql_query("SELECT * FROM department_contracts", conn)
us_data_df = us_data_df.drop(['level_0', 'index'], axis=1)
us_data_df = us_data_df[np.isfinite(us_data_df['Latitude'])]
us_data_df.head()

,Awarding_Agency,Category,Contract_ID,Description,POP_City,POP_State,POP_Zip,Recipient_Name,Subtier_Agency,Subtier_Code,Total_Obligation,Latitude,Longitude
1,Department of Transportation,contract,31520,None,BALTIMORE,MARYLAND,21230,MARYLAND MARITIME INC,Maritime Administration,6938,520169.00,39.263517,-76.623942
2,Department of Transportation,contract,31521,None,BALTIMORE,MARYLAND,21230,MARYLAND MARITIME INC,Maritime Administration,6938,662420.00,39.263517,-76.623942
3,Department of Transportation,contract,31525,None,ORLANDO,FLORIDA,32822,"SIMCOM INTERNATIONAL, INC.",Federal Aviation Administration,6920,39520.00,28.475041,-81.284917
4,Department of Transportation,contract,31526,None,MOJAVE,CALIFORNIA,93501,NATIONAL TEST PILOT SCHOOL INC,Federal Aviation Administration,6920,29950.00,35.044030,-118.252662
5,Department of Transportation,contract,31527,None,FLUSHING,NEW YORK,11371,FLIGHTSAFETY INTERNATIONAL INC,Federal Aviation Administration,6920,59200.00,40.776639,-73.874250

In [45]:
doa_df = us_data_df.loc[us_data_df['Awarding_Agency'] == 'Department of Agriculture']
doa_df['Total_Obligation'] = doa_df['Total_Obligation'].apply(pd.to_numeric)
doa_df = doa_df.sort_values(by=['Total_Obligation'], ascending=False)
doa_df = doa_df.head(10)

# doa_df
print(doa_sum)

310361332.13000005

C:\Users\jdgon\Anaconda3\envs\PythonData\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [41]:
dot_df = us_data_df.loc[us_data_df['Awarding_Agency'] == 'Department of Transportation']
dot_df['Total_Obligation'] = dot_df['Total_Obligation'].apply(pd.to_numeric)
dot_df = dot_df.sort_values(by=['Total_Obligation'], ascending=False)
dot_df = dot_df.head(10)

C:\Users\jdgon\Anaconda3\envs\PythonData\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,Awarding_Agency,Category,Contract_ID,Description,POP_City,POP_State,POP_Zip,Recipient_Name,Subtier_Agency,Subtier_Code,Total_Obligation,Latitude,Longitude
65960,Department of Transportation,contract,8208959,None,ARLINGTON,VIRGINIA,22201,KIEWIT INFRASTRUCTURE CO.,Federal Highway Administration,6925,1.920000e+08,38.884513,-77.093858
270,Department of Transportation,contract,200448,None,YELLOWSTONE NATIONAL PARK,WYOMING,82190,"H-K CONTRACTORS, INC.",Federal Highway Administration,6925,3.986091e+07,44.462085,-110.642441
74219,Department of Transportation,contract,200448,None,YELLOWSTONE NATIONAL PARK,WYOMING,82190,"H-K CONTRACTORS, INC.",Federal Highway Administration,6925,3.986091e+07,44.462085,-110.642441
5919,Department of Transportation,contract,13812906,None,GATLINBURG,TENNESSEE,37738,"APAC-ATLANTIC, INC.",Federal Highway Administration,6925,3.391816e+07,35.694415,-83.464355
31126,Department of Transportation,contract,13810617,None,PORT ANGELES,WASHINGTON,98362,"STRIDER CONSTRUCTION CO., INC.",Federal Highway Administration,6925,2.896741e+07,47.950659,-123.345607
36137,Department of Transportation,contract,31597,None,MARLBOROUGH,MASSACHUSETTS,01752,RAYTHEON COMPANY,Federal Aviation Administration,6920,2.576478e+07,42.347372,-71.536786
61,Department of Transportation,contract,31597,None,MARLBOROUGH,MASSACHUSETTS,01752,RAYTHEON COMPANY,Federal Aviation Administration,6920,2.576478e+07,42.347372,-71.536786
525,Department of Transportation,contract,541005,None,MARLBOROUGH,MASSACHUSETTS,01752,RAYTHEON COMPANY,Federal Aviation Administration,6920,2.446597e+07,42.347372,-71.536786
70076,Department of Transportation,contract,541005,None,MARLBOROUGH,MASSACHUSETTS,01752,RAYTHEON COMPANY,Federal Aviation Administration,6920,2.446597e+07,42.347372,-71.536786
37398,Department of Transportation,contract,13810616,None,HOOD RIVER,OREGON,97031,STELLAR J. CORPORATION,Federal Highway Administration,6925,2.197515e+07,45.629922,-121.616403

In [47]:
doi_df = us_data_df.loc[us_data_df['Awarding_Agency'] == 'Department of the Interior']
doi_df['Total_Obligation'] = doi_df['Total_Obligation'].apply(pd.to_numeric)
doi_df = doi_df.sort_values(by=['Total_Obligation'], ascending=False)
doi_df = doi_df.head(10)

C:\Users\jdgon\Anaconda3\envs\PythonData\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [58]:
doi_sum = doi_df['Total_Obligation'].sum()
dot_sum = dot_df['Total_Obligation'].sum()
doa_sum = doa_df['Total_Obligation'].sum()
total_sum = doi_sum + dot_sum + doa_sum
doi_df['Percentage_of_Total'] = ''
doi_df['Percentage_of_Dept'] = ''

for index, row in doi_df.iterrows():    
    
    row['Percentage_of_Total'].append(int(row['Total_Obligation']) / total_sum)

    
doi_df


# top = [doi_df, doa_df, dot_df]
# top_ten_df = pd.concat(top)
# # top_ten_df = top_ten_df.drop(['index', 'level_0'], axis=1)


# top_ten_df

AttributeError: 'str' object has no attribute 'append'

In [44]:
conn = sqlite3.connect('data.sqlite')

top_ten_df.to_sql("top_ten", conn, if_exists="replace")
us_data_df.to_sql("lat_lon", conn, if_exists="replace")